fastlane_version "1.97.0"

default_platform :ios

platform :ios do

	lane :testing do
		update_fastlane
		
		scan(
			project: "SlidableImage.xcodeproj",
			scheme: "SlidableImage"
		)

		slather(
			proj: "SlidableImage.xcodeproj",
			travis: true,
			coveralls: true,
			scheme: "SlidableImage"
		)
	end

end
