name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pod dependencies
        run: |
          pod install
        shell: bash
      - name: Test
        run: |
          xcodebuild test -workspace SlidableImage.xcworkspace -scheme SlidableImage -destination "platform=iOS Simulator,name=iPhone 11 Pro" -enableCodeCoverage YES
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.3
        with:
          flags: base64,unittests
          file: info.lcov
          fail_ci_if_error: true 